version: '3.7'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    volumes:
      - clickhouse-volume:/bitnami/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  pulsar:
    image: apachepulsar/pulsar-all:latest
    ports:
      - '8080:8080'
      - '6650:6650'
    command: '/start-pulsar.sh'
    environment:
      clusterName: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
      advertisedAddress: 'localhost'
    volumes:
      - ./src/transfer/start-pulsar.sh:/start-pulsar.sh
      - ./src/transfer/connectors/c-cart-add.yaml:/configs/c-cart-add.yaml
      - ./src/transfer/connectors/c-cart-remove.yaml:/configs/c-cart-remove.yaml
      - ./src/transfer/connectors/c-category-view.yaml:/configs/c-category-view.yaml
      - ./src/transfer/connectors/c-coupon-use.yaml:/configs/c-coupon-use.yaml
      - ./src/transfer/connectors/c-product-view.yaml:/configs/c-product-view.yaml
      - ./src/transfer/connectors/c-review-view.yaml:/configs/c-review-view.yaml
      - ./src/transfer/connectors/c-sorting.yaml:/configs/c-sorting.yaml
      - ./src/transfer/run-connectors/rc-cart-add.sh:/rc-cart-add.sh
      - ./src/transfer/run-connectors/rc-cart-remove.sh:/rc-cart-remove.sh
      - ./src/transfer/run-connectors/rc-category-view.sh:/rc-category-view.sh
      - ./src/transfer/run-connectors/rc-coupon-use.sh:/rc-coupon-use.sh
      - ./src/transfer/run-connectors/rc-product-view.sh:/rc-product-view.sh
      - ./src/transfer/run-connectors/rc-review-view.sh:/rc-review-view.sh
      - ./src/transfer/run-connectors/rc-sorting.sh:/rc-sorting.sh

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - '9002:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    networks:
      default:

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/dwms;
      /usr/bin/mc anonymous set private myminio/dwms;
      exit 0;
      "

#  namenode:
#    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#    environment:
#      CLUSTER_NAME: 'test'
#    ports:
#      - '9870:9870'
#    env_file:
#      - src/cold/hadoop.env
#    volumes:
#      - namenode-volume:/hadoop/dfs/name
#
#  datanode:
#    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#    volumes:
#      - datanode-volume:/hadoop/dfs/data
#    env_file:
#      - src/cold/hadoop.env
#    depends_on:
#      - namenode
#
#  resource-manager:
#    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
#    env_file:
#      - src/cold/hadoop.env
#    depends_on:
#      - namenode
#      - datanode
#
#  nodemanager:
#    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
#    env_file:
#      - src/cold/hadoop.env
#    depends_on:
#      - namenode
#      - datanode
#      - resource-manager
#
#  history-server:
#    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
#    volumes:
#      - history-server-volume:/hadoop/yarn/timeline
#    env_file:
#      - src/cold/hadoop.env
#    depends_on:
#      - namenode
#      - datanode
#      - resource-manager
#
#  hive:
#    image: bde2020/hive:2.3.2-postgresql-metastore
#    env_file:
#      - src/cold/hive.env
#    ports:
#      - '10000:10000'
#      - '10002:10002'
#
#  metastore:
#    image: 'bde2020/hive:2.3.2-postgresql-metastore'
#    command: '/opt/hive/bin/hive --service metastore'
#    ports:
#      - "9083:9083"
#    env_file:
#      - src/cold/hive.env
#
#  hive-metastore-postgresql:
#    image: 'bde2020/hive-metastore-postgresql:2.3.0'

volumes:
  clickhouse-volume: {}
#  namenode-volume: {}
#  datanode-volume: {}
#  history-server-volume: {}